### ISSUE TITLE
您好，请问 wenjuan.sql 文件中只是表的创建语句。请问有菜单等基础数据的sql吗？

### ISSUE THREAD

**Issue by ZRRJDD** [failgoddess/Goddess-Questionnaire#1]
![image](https://user-images.githubusercontent.com/30715889/60769506-44a2bb00-a103-11e9-8fa2-6d6f5b617b01.png)

没有菜单 等

**Comment by failgoddess** [comment]
不好意思导出忘导入了，现在已经更新了最新的请重新下载sql脚本

**Comment by ZRRJDD** [comment]
哈哈，没事啊 。我自己补数据，补了好久 ，还是没补完啊
